name: Sync Zoho to GitHub
on:
  schedule:
    - cron: "0 12 * * *"  # Daily at 12 PM UTC
  workflow_dispatch:       # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main           # Explicit branch specification
          fetch-depth: 0      # Full clone (not shallow)

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests gitpython

      - name: Run Sync
        env:
          ZOHO_CLIENT_ID: ${{ secrets.ZOHO_CLIENT_ID }}
          ZOHO_CLIENT_SECRET: ${{ secrets.ZOHO_CLIENT_SECRET }}
          ZOHO_REFRESH_TOKEN: ${{ secrets.ZOHO_REFRESH_TOKEN }}
        run: python fetch_zoho_to_github.py
